# Generated by Django 4.2.6 on 2023-10-14 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="crews",
            field=models.ManyToManyField(to="station.crew"),
        ),
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
    ]
