# Generated by Django 4.2.6 on 2023-10-17 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_alter_order_options_alter_train_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["cargo", "seat"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("trip", "cargo", "seat")},
        ),
    ]
